FROM python:3.9

RUN apt-get update && apt-get -y upgrade

COPY . /app/app

COPY ./FluidR3Mono_GM.sf3 ~/.fluidsynth/default_sound_font.sf2

WORKDIR /app/app

RUN apt-get install -y fluidsynth

RUN pip install -r req.txt

EXPOSE 80

CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "80"]